# src/main/resources/application-prod.yml
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL:jdbc:postgresql://team02-postgresql.postgres.database.azure.com:5432/dev_exam?sslmode=require}
    username: ${DB_USERNAME:alp_team2}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: false
    show-sql: false
