name: Build & Push Docker Image

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set vars (short SHA)
        id: vars
        run: echo "SHORT_SHA=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT

      - name: Detect service name from repo
        id: svc
        shell: bash
        run: |
          NAME="${GITHUB_REPOSITORY#*/}"    # org/repo -> repo
          echo "SERVICE=${NAME}" >> $GITHUB_OUTPUT

      - name: Docker login
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build & Push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          platforms: linux/amd64
          tags: |
            dohhh/damim-ai-tutor:${{ steps.svc.outputs.SERVICE }}-latest
            dohhh/damim-ai-tutor:${{ steps.svc.outputs.SERVICE }}-${{ steps.vars.outputs.SHORT_SHA }}
